# model:
#   temperature: 0.07
#   top_k: 50
#   top_p: 0.9

# new implementation with model specific hyperparams

falcon_mamba:
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  max_new_tokens: 50
  do_sample: true
gemma:
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  max_new_tokens: 50
  do_sample: true
qwen:
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  max_new_tokens: 50
  do_sample: true